services:
  qbitcleaner:
    container_name: qbitfixer
    build:
      context: .
      dockerfile: dockerfile
    image: said287/qbitfixer
    environment:
      QBIT_USERNAME: "${QBIT_USERNAME}"
      QBIT_PASSWORD: "${QBIT_PASSWORD}"
      QBIT_PORT: "${QBIT_PORT}"
      QBIT_IP : "${QBIT_IP}"
      QBIT_TRACKER_STATUS : "${QBIT_TRACKER_STATUS}"
      QBIT_POLLING_INTERVAL : "${QBIT_POLLING_INTERVAL}"
    ports:
      - 8000:8000
    develop:
        watch:
          - action: sync
            path: src
            target: /app/src
          

     



    
