#!/bin/sh

echo "QBIT_USERNAME=$QBIT_USERNAME" >> .env
echo "QBIT_PASSWORD=$QBIT_PASSWORD" >> .env
echo "QBIT_TORRENTS_INFOS_ENDPOINT=$QBIT_TORRENTS_INFOS_ENDPOINT" >> .env
echo "QBIT_LOGIN_ENDPOINT=$QBIT_LOGIN_ENDPOINT" >> .env

npm start